### ISSUE TITLE
Output

### ISSUE THREAD

**Issue by catastrofia** [linsalrob/PhiSpy#6]
Only prophage_tbl.txt as output, no prophage.tbl file on output folder.

**Comment by jaumlrc** [comment]
I have the same issue as catastrofia. 
I have run Phispy using the provided phage “160490.1”, using the command line:

../PhiSpy/./PhiSpy.py -i Test_Organism/160490.1/ -o Test-org-OUT -t 10

**The following is printed in the screen:**
Making Test Set... (need couple of minutes)
Start Classification Algorithm
Using training flag:  10
Done with classification Algorithm
Start evaluation...
Checking prophages in Test-org-OUT/initial_tbl.txt

Finding repeats in pp 1 from 521708 to 579087
Finding repeats in pp 2 from 769726 to 823679
Finding repeats in pp 3 from 1184921 to 1239335
Finding repeats in pp 4 from 1763728 to 1802690
Threshold for fn is  5
Done!!!

**However, in the output dir there are only the files:**
prophage_tbl.txt
tempRepeatDNA.28772.pp.1.fasta
tempRepeatDNA.28772.pp.1.fasta.repeatfinder
tempRepeatDNA.28772.pp.2.fasta
tempRepeatDNA.28772.pp.2.fasta.repeatfinder
tempRepeatDNA.28772.pp.3.fasta
tempRepeatDNA.28772.pp.3.fasta.repeatfinder
tempRepeatDNA.28772.pp.4.fasta
tempRepeatDNA.28772.pp.4.fasta.repeatfinder

I have cloned the Phispy on 02 May 2018.

Could you provide directions on how to solve this issue?

All the best.

**Comment by signetang** [comment]
I realize the question was asked a while ago, but a friend recently had the same issue and we found the solution, so I thought I would just share it.
Go to the script 'evaluation.py' in the folder 'source'. The very last line of the script has been commented out. Just remove the # and when you run PHISPY again the prophage.tbl should be produced.

**Comment by mshakya** [comment]
This issue still persists and @signetang recommendation works. I would be curious to know why this was commented out in first place and if its ok to uncomment it. Perhaps, just forgot to uncomment the line?

**Comment by linsalrob** [comment]
This has now been fixed in the latest code
